### ISSUE TITLE
some issues

### ISSUE THREAD

**Issue by ctf0** [ganvoa/php-code-actions#8]
first many thanks for your work.

second:

- atm if u opened a php file then opened a blade view file afterwards, the code action will be avialable in there aswell which is incorrect.

- the code action should only be avialble on the class declaration line not in the whole file.

- code action should be available in `classes,interface,etc..` only not any php file

**Comment by ganvoa** [comment]
thanks for the report, i will look into those issues. I dont work with blade, but fixing point 2 and 3 should fix point 1 too i think.
